<?php
session_start();
require_once('Controller/backend.php');
require_once('Model/WriteManager.php');
require_once('Model/ChapterManager.php');
require_once('Model/ConnectManager.php');
require_once('../frontend/Model/PostManager.php');
require_once('../frontend/Model/CommentManager.php');
require_once('Model/FlagManager.php');